# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

conda:
  environment: docs/readthedocs/environment.yml

# Set the version of Python and other tools you might need
build:
  image: latest
  commands: |
    cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B build -S . -DBAG_BUILD_SWIG:BOOL=ON -DBAG_BUILD_PYTHON:BOOL=ON -DBAG_BUILD_DOCS:BOOL=ON
    cmake --build build
    mkdir -p _readthedocs/html/
    cp -r build/docs/sphinx/* _readthedocs/html/

# Build documentation in the docs/ directory with Sphinx
#sphinx:
#   configuration: docs/readthedocs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
#python:
#   install:
#   - requirements: docs/requirements.txt