# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-latest"
  commands:
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B build -S . -DBAG_BUILD_PYTHON:BOOL=ON -DBAG_BUILD_DOCS:BOOL=ON
    - cmake --build build -v
    - mkdir -p _readthedocs/html/
    - ls -R build/docs/sphinx
    - cp -r build/docs/sphinx/* _readthedocs/html/
    - ls -R _readthedocs/html

conda:
  environment: docs/readthedocs/environment.yml

# Build documentation in the docs/ directory with Sphinx
#sphinx:
#   configuration: docs/readthedocs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
#python:
#   install:
#   - requirements: docs/requirements.txt