FROM debian:trixie-slim AS builder

RUN apt-get update && \
    apt-get install -y git build-essential cmake ninja-build openssh-client swig doxygen catch2 lcov \
    python3-dev python3-doc python3-venv python3-pip python3-setuptools python3-setuptools-scm python3-wheel \
    python3-pytest python3-pytest-cov python3-pytest-xdist python3-numpy python3-cmake-build-extension \
    python3-gdal gdal-bin \
    curl zip unzip tar \
    libglib2.0-dev \
    libutfcpp-dev \
    libproj-dev \
    libgsf-1-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    zlib1g-dev \
    libpulse-dev \
    wget \
    gdb

RUN pip install --break-system-packages \
    sphinx==6.2.1 \
    numpydoc \
    breathe \
    myst-parser \
    sphinx-automodapi \
    graphviz

# Install libxml2
RUN cd /tmp && \
  wget https://download.gnome.org/sources/libxml2/2.15/libxml2-2.15.1.tar.xz && \
  echo "c008bac08fd5c7b4a87f7b8a71f283fa581d80d80ff8d2efd3b26224c39bc54c  libxml2-2.15.1.tar.xz" > libxml2.sum && \
  shasum -a 256 -c libxml2.sum && \
  tar xf libxml2-2.15.1.tar.xz && \
  cd libxml2-2.15.1 && \
  cmake -B build -G Ninja -S . -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_INSTALL_PREFIX:PATH=/usr \
    -DLIBXML2_WITH_ZLIB=ON -DLIBXML2_WITH_ICONV=OFF -DLIBXML2_WITH_LZMA=OFF -DLIBXML2_WITH_PYTHON=OFF && \
  cmake --build build --target install

# Install HDF5
RUN cd /tmp && \
  wget https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.5/hdf5-1.14.5.tar.gz && \
  echo "ec2e13c52e60f9a01491bb3158cb3778c985697131fc6a342262d32a26e58e44  hdf5-1.14.5.tar.gz" > hdf5.sum && \
  shasum -a 256 -c hdf5.sum && \
  tar xf hdf5-1.14.5.tar.gz && \
  cd hdf5-1.14.5 && \
  cmake -B build -G Ninja -S . -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_INSTALL_PREFIX:PATH=/usr \
    -DHDF5_BUILD_CPP_LIB=ON -DHDF5_BUILD_TOOLS:BOOL=OFF -DBUILD_TESTING:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON \
    -DHDF5_BUILD_HL_LIB:BOOL=ON -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON && \
  cmake --build build --target install

RUN ldconfig

# Install Python dependencies not available from Debian
RUN python3 -m pip install --break-system-packages unittest-xml-reporting

WORKDIR /tmp/bag

ENTRYPOINT ["/bin/bash", "-c"]
